config/routes.rb
Gtr::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users, :accounts, :credits, :debits

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/models/account.rb
class Account < ActiveRecord::Base
  validates_presence_of :name, :balance
  validates_uniqueness_of :name

  has_many :credits
  has_many :debits
end

app/models/credit.rb
class Credit < ActiveRecord::Base
  validates_presence_of :creditor, :amount, :purchase_date
  validates :account, presence: true

  belongs_to :account
end

app/models/debit.rb
class Debit < ActiveRecord::Base
  validates_presence_of :debtor, :amount, :debit_date

  belongs_to :account
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def show
    @account = Account.find(params[:id])
    gon.credits = @account.credits
  end

  def create
    @account = Account.new(params.require(:account).permit(:name, :mint_name, :balance))
    if @account.save
      redirect_to @account
    else
      flash[:notice] = "Could not create account: #{@account.errors.full_messages.join(", ")}"
      @account = Account.new
      render :new
    end
  end

  def new
    @account = Account.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  def index
    @credits = Credit.all
    gon.jbuilder template: "app/views/credits/_all_credits.json.jbuilder"
    @credit = Credit.new
  end

  def create
    credit = Credit.new(params.require(:credit).permit(:creditor, :amount, :purchase_date, :account_id))

    if !credit.save
      flash[:notice] = "Could not add credit: #{credit.errors.full_messages.join(", ")}"
    end
    redirect_to credits_path
  end

end

app/controllers/debits_controller.rb
class DebitsController < ApplicationController
  def index
    @debits = Debit.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @accounts = Account.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
require 'pry'

class UsersController < ApplicationController
  #before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/accounts/new.html.haml
Create a new account

= simple_form_for @account do |f|
  = f.input :name
  = f.input :balance
  = f.button :submit

app/views/accounts/show.html.haml
%h3 Account Information
%p
  Name: #{@account.name}
%p
  Balance: #{@account.balance}
%p
  Credits:
= render partial: 'shared/each_credit', locals: { credits: @account.credits }

app/views/accounts/update.js.erb
$(".users").replaceWith("<%= escape_javascript(render(:partial => 'shared/each_account')) %>");

app/views/credits/index.html.haml
= render partial: 'shared/each_credit', locals: { credits: @credits }

= simple_form_for @credit do |f|
  = f.input :creditor
  = f.input :amount
  = f.input :purchase_date, :as => :string, :input_html => { data: {behaviour: "datepicker"}}
  = f.input :account_id, label: "Account name", collection: Account.all
  = f.button :submit

app/views/debits/index.html.haml
%h3 Listing All Debits

%table.table
  %body.table-striped
    %tr
      %td
        Debtor 
      %td
        Amount
      %td
        Debit Date
      %td
        Account Name
    - @debits.each do |debit|
      %tr
        %td
          #{debit.debtor}
        %td
          #{debit.amount}
        %td
          #{debit.debit_date.strftime("%a %e %b %l:%M %p")}
        %td
          #{debit.account.name}

app/views/home/_each_account.html.haml
- @accounts.each do |account|
  %tr
    %td
      #{link_to account.name, account}
    %td
      #{account.balance}
    %td
      #{account.updated_at.localtime.strftime("%a %e %b %l:%M %p")}
    %td
      = button_to "Update", account_path(account.id), :method => :patch, remote: true

app/views/home/index.html.haml
%h3 Welcome to "Good Thing We're Rich!"

%table.table
  %body.table-striped
    %tr
      %td
        Account 
      %td
        Balance
      %td
        Last Updated
    - @accounts.each do |account|
      %tr
        %td
          #{link_to account.name, account}
        %td
          #{account.balance}
        %td
          #{account.updated_at.localtime.strftime("%a %e %b %l:%M %p")}
    %tr #{link_to "Add an Account", new_account_path}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "GTR", root_path, :class => 'brand'
%ul.nav
  %li 
    = link_to "Credits", credits_path
  %li 
    = link_to "Debits", debits_path
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "GTR"
      %meta{:content => content_for?(:description) ? yield(:description) : "GTR", :name => "description"}
        = include_gon
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = javascript_include_tag "credits"
        = favicon_link_tag
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/shared/_each_account.html.haml
= form_tag account_path(1), method: :patch, remote: true
- @accounts.each do |account|
  %tr
    %td
      #{link_to account.name, account}
    %td
      #{account.balance}
    %td
      #{account.updated_at.localtime.strftime("%a %e %b %l:%M %p")}
    %td
      = submit_tag "Update"

app/views/shared/_each_credit.html.haml
= javascript_include_tag "shared"

.container-fluid
  %table#MyGrid.table.table-bordered.datagrid
    %thead
      %tr
        %th
          %span.datagrid-header-title All Credits
          .datagrid-header-left
          .datagrid-header-right
            .input-append.search
              %input.input-medium{placeholder: "Search", type: "text"}/
              %button.btn
                %i.icon-search
      %tfoot
        %tr
          %th
            .datagrid-footer-left{style: "display:none;"}
              .grid-controls
                %span
                  %span.grid-start
                  \-
                  %span.grid-end
                  of
                  %span.grid-count
                %select.grid-pagesize
                  %option 5
                  %option 10
                %span Per Page
            .datagrid-footer-right{style: "display:none;"}
              .grid-pager
                %button.btn.grid-prevpage
                  %i.icon-chevron-left
                %span Page
                .input-append.dropdown.combobox
                  %input.span1{type: "text"}/
                %span
                  of
                  %span.grid-pages
                %button.btn.grid-nextpage
                  %i.icon-chevron-right

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}